/* eslint-disable import/prefer-default-export */
export const cardsData = [
  {
    id: 1,
    word: 'cry',
    translate: 'плакать',
    image: 'images/cry.jpg',
    audioSrc: 'audio/cry.mp3',
  },
  {
    id: 1,
    word: 'dance',
    translate: 'танцевать',
    image: 'images/dance.jpg',
    audioSrc: 'audio/dance.mp3',
  },
  {
    id: 1,
    word: 'dive',
    translate: 'плавать',
    image: 'images/dive.jpg',
    audioSrc: 'audio/dive.mp3',
  },
  {
    id: 1,
    word: 'draw',
    translate: 'рисовать',
    image: 'images/draw.jpg',
    audioSrc: 'audio/draw.mp3',
  },
  {
    id: 1,
    word: 'fish',
    translate: 'рыбачить',
    image: 'images/fish.jpg',
    audioSrc: 'audio/fish.mp3',
  },
  {
    id: 1,
    word: 'fly',
    translate: 'летать',
    image: 'images/fly.jpg',
    audioSrc: 'audio/fly.mp3',
  },
  {
    id: 1,
    word: 'hug',
    translate: 'обнимать',
    image: 'images/hug.jpg',
    audioSrc: 'audio/hug.mp3',
  },
  {
    id: 1,
    word: 'jump',
    translate: 'прыгать',
    image: 'images/jump.jpg',
    audioSrc: 'audio/jump.mp3',
  },
  {
    id: 2,
    word: 'open',
    translate: 'открывать',
    image: 'images/open.jpg',
    audioSrc: 'audio/open.mp3',
  },
  {
    id: 2,
    word: 'play',
    translate: 'играть',
    image: 'images/play.jpg',
    audioSrc: 'audio/play.mp3',
  },
  {
    id: 2,
    word: 'point',
    translate: 'указывать',
    image: 'images/point.jpg',
    audioSrc: 'audio/point.mp3',
  },
  {
    id: 2,
    word: 'ride',
    translate: 'ездить',
    image: 'images/ride.jpg',
    audioSrc: 'audio/ride.mp3',
  },
  {
    id: 2,
    word: 'run',
    translate: 'бегать',
    image: 'images/run.jpg',
    audioSrc: 'audio/run.mp3',
  },
  {
    id: 2,
    word: 'sing',
    translate: 'петь',
    image: 'images/sing.jpg',
    audioSrc: 'audio/sing.mp3',
  },
  {
    id: 2,
    word: 'skip',
    translate: 'пропускать, прыгать',
    image: 'images/skip.jpg',
    audioSrc: 'audio/skip.mp3',
  },
  {
    id: 2,
    word: 'swim',
    translate: 'плавать',
    image: 'images/swim.jpg',
    audioSrc: 'audio/swim.mp3',
  },
  {
    id: 3,
    word: 'argue',
    translate: 'спорить',
    image: 'images/argue.jpg',
    audioSrc: 'audio/argue.mp3',
  },
  {
    id: 3,
    word: 'build',
    translate: 'строить',
    image: 'images/build.jpg',
    audioSrc: 'audio/build.mp3',
  },
  {
    id: 3,
    word: 'carry',
    translate: 'нести',
    image: 'images/carry.jpg',
    audioSrc: 'audio/carry.mp3',
  },
  {
    id: 3,
    word: 'catch',
    translate: 'ловить',
    image: 'images/catch.jpg',
    audioSrc: 'audio/catch.mp3',
  },
  {
    id: 3,
    word: 'drive',
    translate: 'ездить',
    image: 'images/drive.jpg',
    audioSrc: 'audio/drive.mp3',
  },
  {
    id: 3,
    word: 'drop',
    translate: 'падать',
    image: 'images/drop.jpg',
    audioSrc: 'audio/drop.mp3',
  },
  {
    id: 3,
    word: 'pull',
    translate: 'тянуть',
    image: 'images/pull.jpg',
    audioSrc: 'audio/pull.mp3',
  },
  {
    id: 3,
    word: 'push',
    translate: 'толкать',
    image: 'images/push.jpg',
    audioSrc: 'audio/push.mp3',
  },
  {
    id: 4,
    word: 'big',
    translate: 'большой',
    image: 'images/big.jpg',
    audioSrc: 'audio/big.mp3',
  },
  {
    id: 4,
    word: 'small',
    translate: 'маленький',
    image: 'images/small.jpg',
    audioSrc: 'audio/small.mp3',
  },
  {
    id: 4,
    word: 'fast',
    translate: 'быстрый',
    image: 'images/fast.jpg',
    audioSrc: 'audio/fast.mp3',
  },
  {
    id: 4,
    word: 'slow',
    translate: 'медленный',
    image: 'images/slow.jpg',
    audioSrc: 'audio/slow.mp3',
  },
  {
    id: 4,
    word: 'friendly',
    translate: 'дружелюбный',
    image: 'images/friendly.jpg',
    audioSrc: 'audio/friendly.mp3',
  },
  {
    id: 4,
    word: 'unfriendly',
    translate: 'враждебный',
    image: 'images/unfriendly.jpg',
    audioSrc: 'audio/unfriendly.mp3',
  },
  {
    id: 4,
    word: 'young',
    translate: 'молодой',
    image: 'images/young.jpg',
    audioSrc: 'audio/young.mp3',
  },
  {
    id: 4,
    word: 'old',
    translate: 'старый',
    image: 'images/old.jpg',
    audioSrc: 'audio/old.mp3',
  },
  {
    id: 5,
    word: 'cat',
    translate: 'кот',
    image: 'images/cat.jpg',
    audioSrc: 'audio/cat.mp3',
  },
  {
    id: 5,
    word: 'chick',
    translate: 'цыпленок',
    image: 'images/chick.jpg',
    audioSrc: 'audio/chick.mp3',
  },
  {
    id: 5,
    word: 'chicken',
    translate: 'курица',
    image: 'images/chicken.jpg',
    audioSrc: 'audio/chicken.mp3',
  },
  {
    id: 5,
    word: 'dog',
    translate: 'собака',
    image: 'images/dog.jpg',
    audioSrc: 'audio/dog.mp3',
  },
  {
    id: 5,
    word: 'horse',
    translate: 'лошадь',
    image: 'images/horse.jpg',
    audioSrc: 'audio/horse.mp3',
  },
  {
    id: 5,
    word: 'pig',
    translate: 'свинья',
    image: 'images/pig.jpg',
    audioSrc: 'audio/pig.mp3',
  },
  {
    id: 5,
    word: 'rabbit',
    translate: 'кролик',
    image: 'images/rabbit.jpg',
    audioSrc: 'audio/rabbit.mp3',
  },
  {
    id: 5,
    word: 'sheep',
    translate: 'овца',
    image: 'images/sheep.jpg',
    audioSrc: 'audio/sheep.mp3',
  },
  {
    id: 6,
    word: 'bird',
    translate: 'птица',
    image: 'images/bird.jpg',
    audioSrc: 'audio/bird.mp3',
  },
  {
    id: 6,
    word: 'fish',
    translate: 'рыба',
    image: 'images/fish.jpg',
    audioSrc: 'audio/fish.mp3',
  },
  {
    id: 6,
    word: 'frog',
    translate: 'лягушка',
    image: 'images/frog.jpg',
    audioSrc: 'audio/frog.mp3',
  },
  {
    id: 6,
    word: 'giraffe',
    translate: 'жираф',
    image: 'images/giraffe.jpg',
    audioSrc: 'audio/giraffe.mp3',
  },
  {
    id: 6,
    word: 'lion',
    translate: 'лев',
    image: 'images/lion.jpg',
    audioSrc: 'audio/lion.mp3',
  },
  {
    id: 6,
    word: 'mouse',
    translate: 'мышь',
    image: 'images/mouse.jpg',
    audioSrc: 'audio/mouse.mp3',
  },
  {
    id: 6,
    word: 'turtle',
    translate: 'черепаха',
    image: 'images/turtle.jpg',
    audioSrc: 'audio/turtle.mp3',
  },
  {
    id: 6,
    word: 'dolphin',
    translate: 'дельфин',
    image: 'images/dolphin.jpg',
    audioSrc: 'audio/dolphin.mp3',
  },
  {
    id: 7,
    word: 'skirt',
    translate: 'юбка',
    image: 'images/skirt.jpg',
    audioSrc: 'audio/skirt.mp3',
  },
  {
    id: 7,
    word: 'pants',
    translate: 'брюки',
    image: 'images/pants.jpg',
    audioSrc: 'audio/pants.mp3',
  },
  {
    id: 7,
    word: 'blouse',
    translate: 'блузка',
    image: 'images/blouse.jpg',
    audioSrc: 'audio/blouse.mp3',
  },
  {
    id: 7,
    word: 'dress',
    translate: 'платье',
    image: 'images/dress.jpg',
    audioSrc: 'audio/dress.mp3',
  },
  {
    id: 7,
    word: 'boot',
    translate: 'ботинок',
    image: 'images/boot.jpg',
    audioSrc: 'audio/boot.mp3',
  },
  {
    id: 7,
    word: 'shirt',
    translate: 'рубашка',
    image: 'images/shirt.jpg',
    audioSrc: 'audio/shirt.mp3',
  },
  {
    id: 7,
    word: 'coat',
    translate: 'пальто',
    image: 'images/coat.jpg',
    audioSrc: 'audio/coat.mp3',
  },
  {
    id: 7,
    word: 'shoes',
    translate: 'туфли',
    image: 'images/shoes.jpg',
    audioSrc: 'audio/shoes.mp3',
  },
  {
    id: 8,
    word: 'sad',
    translate: 'грустный',
    image: 'images/sad.jpg',
    audioSrc: 'audio/sad.mp3',
  },
  {
    id: 8,
    word: 'angry',
    translate: 'сердитый',
    image: 'images/angry.jpg',
    audioSrc: 'audio/angry.mp3',
  },
  {
    id: 8,
    word: 'happy',
    translate: 'счастливый',
    image: 'images/happy.jpg',
    audioSrc: 'audio/happy.mp3',
  },
  {
    id: 8,
    word: 'tired',
    translate: 'уставший',
    image: 'images/tired.jpg',
    audioSrc: 'audio/tired.mp3',
  },
  {
    id: 8,
    word: 'surprised',
    translate: 'удивленный',
    image: 'images/surprised.jpg',
    audioSrc: 'audio/surprised.mp3',
  },
  {
    id: 8,
    word: 'scared',
    translate: 'напуганный',
    image: 'images/scared.jpg',
    audioSrc: 'audio/scared.mp3',
  },
  {
    id: 8,
    word: 'smile',
    translate: 'улыбка',
    image: 'images/smile.jpg',
    audioSrc: 'audio/smile.mp3',
  },
  {
    id: 8,
    word: 'laugh',
    translate: 'смех',
    image: 'images/laugh.jpg',
    audioSrc: 'audio/laugh.mp3',
  },
];
